import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/car.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube004.geometry}
        material={materials.taillights}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube014.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube015.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube017.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube018.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube019.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube020.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube021.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube025.geometry}
        material={materials.Material}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube026.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube027.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube028.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube034.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube035.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube036.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube037.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube038.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube039.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cube040.geometry}
        material={materials.headlights}
      />
    </group>
  );
}

useGLTF.preload("/car.glb");
